Non-working builder for Material
I can't quite figure out how to do this right. The problem is the
pattern field, which is in a box. I get this compile error:

    cannot move out of `*__self_1_7` which is behind a shared reference

    move occurs because `*__self_1_7` has type `std::boxed::Box<dyn pattern::pattern::Pattern>`, which does not implement the `Copy` traitrustc(E0507)
    material.rs(51, 5): move occurs because `*__self_1_7` has type `std::boxed::Box<dyn pattern::pattern::Pattern>`, which does not implement the `Copy` trait